### PR TITLE
Add language support

### PR DESCRIPTION
**Pull request by fviejobueno**

### CODE REVIEW

**Comment by DuaelFr** [comment]
Hi! I strongly support your change but I think that you should not split strings too much because some languages would not be able to translate the widget this way. Would it be possible to use less variables to allow each language to deal with its own constraints?

**Comment by fviejobueno** [comment]
@DuaelFr i just refactored the yaml files to include multiline text with html tags, using body, ready and footer as placeholders.

**Comment by miloskroulik** [comment]
Is there anything I can do to help you with this PR? Can you ping me when it's ready for testing, please?

**Comment by fviejobueno** [comment]
@miloskroulik Hello, the PR is ready for testing.

**Comment by DuaelFr** [comment]
Hi folks!

I feel like I misguided you a bit. Thank you so much to have updated the way strings were handled to make them translatable for everyone. I think you went a bit too far, though. 

It's important to let people translate each string as a whole but they don't need to be able to replace their wrapper (and I suppose that it would be a mess if they did). I suggest to move the markup that wraps the strings (`<p>`, `<button>`, etc.) in the template and only keep the content in the translation files.

You're close to the goal!
(I'll make the French translation once this is commited)

**Comment by DuaelFr** [comment]
👍

**Comment by DuaelFr** [comment]
@fviejobueno nice catch on the date format! I believe other languages will need this too. Spannish is "[day number] de [month name]" for example. 
Wouldn't it be better to use [toLocaleDateString() like show in the example](https://stackoverflow.com/a/34015511)?

**Comment by dtoakley** [comment]
Agree @DuaelFr -- I've updated it with master, and with that suggestion. This is much better as it avoids hardcoding translations :)

**Comment by dtoakley** [comment]
I throughly x-browser/os tested this using the staging bucket: http://stage.digitalclimatestrike.net/demo.html?language=de Looks good. Merged done and closing this issue.

**Pull request merged**
