### PR TITLE
Add a basic Czech localization.

### PR DESCRIPTION
**Pull request by miloskroulik**
I've added a basic Czech localization. Please let me know if I'm missing something important, it seems to be working reasonably well for me.

### CODE REVIEW

**Comment by miloskroulik** [comment]
As there are no comments and the time is pressing, I've decided to merge this myself. I hope that no kittens are going to be harmed.

**Comment by dtoakley** [comment]
Thanks for the branch @miloskroulik awesome to get Czech added. However this implementation for is broken in a few ways (for cs only though):
1. getLanguage in widget.js needs to be updated to support 'cs' as a language
2. Removing the <span class="dcs-website-name__prefix"></span> from the translation yml breaks handleCustomWebsiteName on line 50
3. Without adding a URL for 'cs' in the GLOBAL_CLIMATE_STRIKE_URLS const, the links don't go anyway. 

We should also update the README to folks know Czech is now available. 

Now it shouldn't take this many changes to add a language, so we have lots to improve. it *should* be as simple as adding a new .yml file. However we're not quite there yet :) I'll create a new issue to help refactor some of this code so these sort of bugs don't get introduced, or are unlikely to be introduced. 

Going forward, I'd suggest the follow to our dev workflow: 
1. PRs get reviewed by someone familiar with the codebase before being merged in. For now, I'm happy to be that person and will generally respond within 24 hours (unless it's the weekend). 
2. Changes are thoroughly tested locally before PR is created. This means testing the footer banner, full page view, full page with close view and links in all cases. I caught the issues above by doing this :) 

Very open to tweaks to these suggestions. I don't to be process focused or make any feel restricted in how to contribute. But I also want to keep master bug free / stable given we have 100+ websites already using the widget (a good problem to have!)

**Comment by dtoakley** [comment]
I'm going to create a new branch with the fixes, and would love you to review and test locally before we merge it down, @miloskroulik

**Comment by miloskroulik** [comment]
That would be awesome, sorry for not adhering to the standard development process here. I've also created another PR with some notes about localization added, it would be probably good to fix it as part of correcting issues mentioned here.

**Comment by dtoakley** [comment]
Agree, updating the CONTRIBUTING is a great idea. 

Here's the new PR: https://github.com/fightforthefuture/digital-climate-strike/pull/65/files

**Pull request merged**
